"""Renamed TeacherStudent to Appointment

Revision ID: 02fb0252a976
Revises: 
Create Date: 2025-04-17 16:33:44.543069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fb0252a976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('lesson_datetime', sa.DateTime(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_appointments_student_id_students')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_appointments_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('teacher_student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cost', sa.INTEGER(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_teacher_student_student_id_students'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='fk_teacher_student_teacher_id_teachers'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('appointments')
    # ### end Alembic commands ###
